# Site settings
title: Marco Fernandes
email: marco@marcofernandes.com
description: "Drupal all rounder developer. Hybrid mobile app and Javascript enthusiast. Big fan of KISS, not the band but the principle. Developer at <a href='http://front.no'>Frontkom</a>."
baseurl: ""
url: "http://marcofernandes.com"
twitter_username: marcoffernandes
github_username:  vonloxx

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed

exclude:
  - "bower_components"
  - "bower.json"
